name: Build ARM64 Package

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test
      - name: Download and Unpack UPX
        run: |
          wget "https://github.com/upx/upx/releases/download/v3.96/upx-3.96-arm64_linux.tar.xz" -O "/home/runner/work/upx-3.96-arm64_linux.tar.xz"
          tar xvf /home/runner/work/upx-3.96-arm64_linux.tar.xz
      - name: Install Flit
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install flit
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: flit install --symlink
      - name: Set API Keys
        run: |
          echo "OPEN_WEATHER_MAP_API_KEY = '${{ secrets.OPEN_WEATHER_MAP_API_KEY }}'" > ./anton/utils/constants.py
      - name: Build
        run: bash ./scripts/build_ARM64.sh ${{ secrets.PYI_BLOCK_CIPHER_KEY }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: anton_win10x64_build
          path: |
            **/Anton.*
          retention-days: 1

