name: Build ARM64 Package

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build
        id: build
        run: |
          - docker buildx build ./.github/actions/arm64-build/Dockerfile --platform linux/amd64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: anton_win10x64_build
          path: |
            **/Anton.*
          retention-days: 1

