name: Build ARM64 Package

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Set API Keys
        run: |
          echo "OPEN_WEATHER_MAP_API_KEY = '${{ secrets.OPEN_WEATHER_MAP_API_KEY }}'" > ./anton/utils/constants.py

      - name: Build
        run: |
          docker build --platform linux/amd64 --tag anton --build-arg KEY=${{ secrets.PYI_BLOCK_CIPHER_KEY }} .

      - name: Export Dist
        run: |
          docker ps
          docker cp moby/buildkit:buildx-stable-1:Anton/dist/Anton "./Anton"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: anton_arm64_build
          path: |
            **/Anton
          retention-days: 1

