name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, opened ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test
      - name: Install Flit
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install flit
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: flit install --symlink
      - name: Set API Keys
        run: |
          echo "OPEN_WEATHER_MAP_API_KEY = '${{ secrets.OPEN_WEATHER_MAP_API_KEY }}'" > ./anton/utils/constants.py
          echo "PYI_BLOCK_CIPHER_KEY = '${{ secrets.PYI_BLOCK_CIPHER_KEY }}'" >> ./anton/utils/constants.py
      - name: Lint
        run: bash scripts/lint.sh
        if: always()
      - name: Test
        run: bash scripts/test.sh
        if: always()
      - name: Remove API Keys
        run: |
          rm -f ./anton/utils/constants.py
        if: always()
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pytest-logs
          path: |
            **/pytest-logs.txt
            **/Anton.db
            **/Anton.log
            **/htmlcov/*
          retention-days: 1
        if: always()
      - name: Upload Coverage
        uses: codecov/codecov-action@v2
